### ISSUE TITLE
Compile error on CentOS 7

### ISSUE THREAD

**Issue by vipera7** [oetiker/rrdtool-1.x#1000] opened 2019-04-15 13:08 UTC
I'm trying to install rrdtool on my instance running on CentOS 7. I created a script which install all dependencies. Here is my script : 

```
#!/bin/bash
yum update -y && yum upgrade -y && yum install wget -y
yum groupinstall "Development Tools" -y
BUILD_DIR=/tmp/rrdbuild
INSTALL_DIR=/opt/rrdtool-1.7.1
mkdir -p $BUILD_DIR
cd $BUILD_DIR
wget https://oss.oetiker.ch/rrdtool/pub/rrdtool-1.7.1.tar.gz
gunzip -c rrdtool-1.7.1.tar.gz | tar xf -
export PKG_CONFIG_PATH=${INSTALL_DIR}/lib/pkgconfig
export PATH=$INSTALL_DIR/bin:$PATH
export LDFLAGS="-Wl,--rpath -Wl,${INSTALL_DIR}/lib"
export MAKE=make

#pkgconfig
wget http://pkgconfig.freedesktop.org/releases/pkg-config-0.23.tar.gz
gunzip -c pkg-config-0.23.tar.gz | tar xf -
cd pkg-config-0.23
./configure --prefix=$INSTALL_DIR CFLAGS="-O3 -fPIC"
$MAKE
$MAKE install
export PKG_CONFIG=$INSTALL_DIR/bin/pkg-config

#zlib
cd $BUILD_DIR
wget https://oss.oetiker.ch/rrdtool/pub/libs/zlib-1.2.3.tar.gz
gunzip -c zlib-1.2.3.tar.gz | tar xf -
cd zlib-1.2.3
./configure --prefix=$INSTALL_DIR CFLAGS="-O3 -fPIC" --shared
$MAKE
$MAKE install

#libpng
cd $BUILD_DIR
wget https://oss.oetiker.ch/rrdtool/pub/libs/libpng-1.2.18.tar.gz
gunzip -c libpng-1.2.18.tar.gz | tar xf -
cd libpng-1.2.18
env CFLAGS="-O3 -fPIC" ./configure --prefix=$INSTALL_DIR
$MAKE
$MAKE install

#freetype
cd $BUILD_DIR
wget https://oss.oetiker.ch/rrdtool/pub/libs/freetype-2.3.5.tar.gz
gunzip -c freetype-2.3.5.tar.gz | tar xf -
cd freetype-2.3.5
./configure --prefix=$INSTALL_DIR CFLAGS="-O3 -fPIC"
$MAKE
$MAKE install

#LibXML2
cd $BUILD_DIR
wget https://oss.oetiker.ch/rrdtool/pub/libs/libxml2-2.6.32.tar.gz
gunzip -c libxml2-2.6.32.tar.gz | tar xf -
cd libxml2-2.6.32
./configure --prefix=$INSTALL_DIR CFLAGS="-O3 -fPIC"
$MAKE
$MAKE install

#fontconfig
cd $BUILD_DIR
wget https://oss.oetiker.ch/rrdtool/pub/libs/fontconfig-2.4.2.tar.gz
gunzip -c fontconfig-2.4.2.tar.gz   | tar xf -
cd fontconfig-2.4.2
./configure --prefix=$INSTALL_DIR CFLAGS="-O3 -fPIC" --with-freetype-config=$INSTALL_DIR/bin/freetype-config
$MAKE
$MAKE install

#Pixman
cd $BUILD_DIR
wget https://oss.oetiker.ch/rrdtool/pub/libs/pixman-0.10.0.tar.gz
gunzip -c pixman-0.10.0.tar.gz  | tar xf -
cd pixman-0.10.0
./configure --prefix=$INSTALL_DIR CFLAGS="-O3 -fPIC"
$MAKE
$MAKE install

#Cairo
cd $BUILD_DIR
wget https://oss.oetiker.ch/rrdtool/pub/libs/cairo-1.6.4.tar.gz
gunzip -c cairo-1.6.4.tar.gz   | tar xf -
cd cairo-1.6.4
./configure --prefix=$INSTALL_DIR \
   --enable-xlib=no \
   --enable-xlib-render=no \
   --enable-win32=no \
   CFLAGS="-O3 -fPIC"
$MAKE
$MAKE install

#Glib
cd $BUILD_DIR
wget https://oss.oetiker.ch/rrdtool/pub/libs/glib-2.15.4.tar.gz
gunzip -c glib-2.15.4.tar.gz  | tar xf -
cd glib-2.15.4
./configure --prefix=$INSTALL_DIR CFLAGS="-O3 -fPIC"
$MAKE
$MAKE install

#Pango
cd $BUILD_DIR
wget https://oss.oetiker.ch/rrdtool/pub/libs/pango-1.21.1.tar.bz2
bunzip2 -c pango-1.21.1.tar.bz2 | tar xf -
cd pango-1.21.1
./configure --prefix=$INSTALL_DIR CFLAGS="-O3 -fPIC" --without-x
$MAKE
$MAKE install

#rrdtool 
cd $BUILD_DIR/rrdtool-1.7.1
./configure --prefix=$INSTALL_DIR --disable-tcl --disable-python
$MAKE clean
$MAKE
$MAKE install
```

**To Reproduce**
1. Run a clean CentOS 7 machine
2. Run the script

**Expected behavior**
I expect to install rrdtool.

Here is the error I get from the compilation : 

```
checking for g_regex_new... yes
checking for png_access_version_number in -lpng... no
checking for pkg-config... (cached) pkg-config
configure: WARNING:
----------------------------------------------------------------------------
* I found a copy of pkgconfig, but there is no libpng.pc file around.
  You may want to set the PKG_CONFIG_PATH variable to point to its
  location.
----------------------------------------------------------------------------

configure: WARNING:
----------------------------------------------------------------------------
* I could not find a working copy of libpng. Check config.log for hints on why
  this is the case. Maybe you need to set LDFLAGS and CPPFLAGS appropriately
  so that compiler and the linker can find libpng and its header files. If
  you have not installed libpng, you can get it either from its original home on

     ftp://ftp.simplesystems.org/pub/libpng/png/src/

  You can find also find an archive copy on

     http://oss.oetiker.ch/rrdtool/pub/libs

  The last tested version of libpng is 1.4.8.

       LIBS=-lgthread-2.0 -lm  -lglib-2.0
   LDFLAGS=-Wl,--rpath -Wl,/opt/rrdtool-1.7.1/lib -L/opt/rrdtool-1.7.1/lib
  CPPFLAGS= -I/opt/rrdtool-1.7.1/include/glib-2.0 -I/opt/rrdtool-1.7.1/lib/glib-2.0/include

----------------------------------------------------------------------------

checking for pango_cairo_context_set_font_options in -lpangocairo-1.0... no
checking for pkg-config... (cached) pkg-config
configure: WARNING:
----------------------------------------------------------------------------
* I found a copy of pkgconfig, but there is no pangocairo.pc file around.
  You may want to set the PKG_CONFIG_PATH variable to point to its
  location.
----------------------------------------------------------------------------

configure: WARNING:
----------------------------------------------------------------------------
* I could not find a working copy of pangocairo. Check config.log for hints on why
  this is the case. Maybe you need to set LDFLAGS and CPPFLAGS appropriately
  so that compiler and the linker can find libpangocairo-1.0 and its header files. If
  you have not installed pangocairo, you can get it either from its original home on

     http://ftp.gnome.org/pub/GNOME/sources/pango/1.28

  You can find also find an archive copy on

     http://oss.oetiker.ch/rrdtool/pub/libs

  The last tested version of pangocairo is 1.28.4.

       LIBS=-lgthread-2.0 -lm  -lglib-2.0
   LDFLAGS=-Wl,--rpath -Wl,/opt/rrdtool-1.7.1/lib -L/opt/rrdtool-1.7.1/lib
  CPPFLAGS= -I/opt/rrdtool-1.7.1/include/glib-2.0 -I/opt/rrdtool-1.7.1/lib/glib-2.0/include

----------------------------------------------------------------------------

checking for g_object_unref in -lgobject-2.0... yes
checking glib-object.h usability... yes
checking glib-object.h presence... yes
checking for glib-object.h... yes
checking for pango_font_map_create_context... no
checking for xmlParseFile in -lxml2... no
checking for pkg-config... (cached) pkg-config
configure: WARNING:
----------------------------------------------------------------------------
* I found a copy of pkgconfig, but there is no libxml-2.0.pc file around.
  You may want to set the PKG_CONFIG_PATH variable to point to its
  location.
----------------------------------------------------------------------------

configure: WARNING:
----------------------------------------------------------------------------
* I could not find a working copy of libxml-2.0. Check config.log for hints on why
  this is the case. Maybe you need to set LDFLAGS and CPPFLAGS appropriately
  so that compiler and the linker can find libxml2 and its header files. If
  you have not installed libxml-2.0, you can get it either from its original home on

     http://xmlsoft.org/downloads.html

  You can find also find an archive copy on

     http://oss.oetiker.ch/rrdtool/pub/libs

  The last tested version of libxml-2.0 is 2.7.8.

       LIBS=-lgobject-2.0 -lgthread-2.0 -lm  -lglib-2.0
   LDFLAGS=-Wl,--rpath -Wl,/opt/rrdtool-1.7.1/lib -L/opt/rrdtool-1.7.1/lib
  CPPFLAGS= -I/opt/rrdtool-1.7.1/include/glib-2.0 -I/opt/rrdtool-1.7.1/lib/glib-2.0/include

----------------------------------------------------------------------------

configure: error: Please fix the library issues listed above and try again.
make: *** No rule to make target `clean'.  Stop.
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target `install'.  Stop.


```

I have no idea how to install all the dependencies. I installed them like it said on the doc.

**Comment by vipera7** [comment] 2019-04-15 13:53
I installed succesfully the dependencies with : 

`yum install cairo-devel libxml2-devel pango-devel pango libpng-devel freetype freetype-devel libart_lgpl-devel perl-devel -y`

I configured it with `./configure` with success.


When I try to use `make` I got the following error : 

```
Running Mkbootstrap for RRDs ()
chmod 644 RRDs.bs
rm -f blib/arch/auto/RRDs/RRDs.so
gcc  -shared -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -Wl,-z,relro  RRDs.o -L/home/rrdbuild/rrdtool-1.7.1/src/.libs/ -Wl,--rpath -Wl,/opt/rrdtool-1.7.1/lib -lrrd  -o blib/arch/auto/RRDs/RRDs.so        \
        \

chmod 755 blib/arch/auto/RRDs/RRDs.so
cp RRDs.bs blib/arch/auto/RRDs/RRDs.bs
chmod 644 blib/arch/auto/RRDs/RRDs.bs
Manifying blib/man3/RRDs.3pm
make[3]: Leaving directory `/home/rrdbuild/rrdtool-1.7.1/bindings/perl-shared'
mkdir -p ./perl-shared
mkdir -p ./python
cd ./python \
  && ( test -e rrdtoolmodule.c || ln -s /home/rrdbuild/rrdtool-1.7.1/bindings/python/rrdtoolmodule.c ) \
          && env \
               ABS_TOP_SRCDIR=/home/rrdbuild/rrdtool-1.7.1 \
               ABS_TOP_BUILDDIR=/home/rrdbuild/rrdtool-1.7.1 \
               LD_RUN_PATH=/opt/rrdtool-1.7.1/lib \
               /usr/bin/python /home/rrdbuild/rrdtool-1.7.1/bindings/python/setup.py build_ext --rpath=/opt/rrdtool-1.7.1/lib \
          && env \
               ABS_TOP_SRCDIR=/home/rrdbuild/rrdtool-1.7.1 \
               ABS_TOP_BUILDDIR=/home/rrdbuild/rrdtool-1.7.1 \
               /usr/bin/python /home/rrdbuild/rrdtool-1.7.1/bindings/python/setup.py build
running build_ext
running build
running build_ext
make[2]: Leaving directory `/home/rrdbuild/rrdtool-1.7.1/bindings'
make[1]: Leaving directory `/home/rrdbuild/rrdtool-1.7.1/bindings'
Making all in tests
make[1]: Entering directory `/home/rrdbuild/rrdtool-1.7.1/tests'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/home/rrdbuild/rrdtool-1.7.1/tests'
Making all in etc
make[1]: Entering directory `/home/rrdbuild/rrdtool-1.7.1/etc'
make[1]: *** No rule to make target `etc/rrdcached.socket', needed by `all-am'.  Stop.
make[1]: Leaving directory `/home/rrdbuild/rrdtool-1.7.1/etc'
make: *** [all-recursive] Error 1


```

And the error I get with `make install` : 

```
make[3]: Entering directory `/home/rrdbuild/rrdtool-1.7.1/bindings'
make[3]: Nothing to be done for `install-exec-am'.
  GEN      install-data-local
make[4]: Entering directory `/home/rrdbuild/rrdtool-1.7.1/bindings/perl-piped'
Manifying blib/man3/RRDp.3pm
Appending installation info to /opt/rrdtool-1.7.1/lib/perl/5.16.3/x86_64-linux-thread-multi/perllocal.pod
make[4]: Leaving directory `/home/rrdbuild/rrdtool-1.7.1/bindings/perl-piped'
  GEN      install-data-local
make[4]: Entering directory `/home/rrdbuild/rrdtool-1.7.1/bindings/perl-shared'
Files found in blib/arch: installing files in blib/lib into architecture dependent library tree
Appending installation info to /opt/rrdtool-1.7.1/lib/perl/5.16.3/x86_64-linux-thread-multi/perllocal.pod
make[4]: Leaving directory `/home/rrdbuild/rrdtool-1.7.1/bindings/perl-shared'
  GEN      install-data-local
  GEN      install-data-local
running install
Checking .pth file support in opt/rrdtool-1.7.1/lib64/python2.7/site-packages/
/usr/bin/python -E -c pass
TEST FAILED: opt/rrdtool-1.7.1/lib64/python2.7/site-packages/ does NOT support .pth files
error: bad install directory or PYTHONPATH

You are attempting to install a package to a directory that is not
on PYTHONPATH and which Python does not read ".pth" files from.  The
installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    opt/rrdtool-1.7.1/lib64/python2.7/site-packages/

and your PYTHONPATH environment variable currently contains:

    ''

Here are some of your options for correcting the problem:

* You can choose a different installation directory, i.e., one that is
  on PYTHONPATH or supports .pth files

* You can add the installation directory to the PYTHONPATH environment
  variable.  (It must then also be on PYTHONPATH whenever you run
  Python and want to use the package(s) you are installing.)

* You can set up the installation directory to support ".pth" files by
  using one of the approaches described here:

  https://pythonhosted.org/setuptools/easy_install.html#custom-installation-locations

Please make the appropriate changes for your system and try again.
make[3]: Leaving directory `/home/rrdbuild/rrdtool-1.7.1/bindings'
make[2]: Leaving directory `/home/rrdbuild/rrdtool-1.7.1/bindings'
make[1]: Leaving directory `/home/rrdbuild/rrdtool-1.7.1/bindings'
Making install in tests
make[1]: Entering directory `/home/rrdbuild/rrdtool-1.7.1/tests'
make[2]: Entering directory `/home/rrdbuild/rrdtool-1.7.1/tests'
make[2]: Nothing to be done for `install-exec-am'.
make[2]: Nothing to be done for `install-data-am'.
make[2]: Leaving directory `/home/rrdbuild/rrdtool-1.7.1/tests'
make[1]: Leaving directory `/home/rrdbuild/rrdtool-1.7.1/tests'
Making install in etc
make[1]: Entering directory `/home/rrdbuild/rrdtool-1.7.1/etc'
make[1]: *** No rule to make target `etc/rrdcached.socket', needed by `all-am'.  Stop.
make[1]: Leaving directory `/home/rrdbuild/rrdtool-1.7.1/etc'
make: *** [install-recursive] Error 1

```

**Comment by c72578** [comment] 2019-04-16 12:00
This is a duplicate of https://github.com/oetiker/rrdtool-1.x/issues/967
It has been fixed in master, see commit https://github.com/oetiker/rrdtool-1.x/commit/865a9bade72f93cf72ca59954c6df01e8c48915d and PR https://github.com/oetiker/rrdtool-1.x/pull/960

**Comment by vipera7** [comment] 2019-04-18 07:08
Thank you for the answer, but I downloaded the lastest version of rrdtool.

**Comment by c72578** [comment] 2019-04-18 08:01
The logs above mention rrdtool-1.7.1.tar.gz instead of current master.
You can get the current git master e.g. using git:
`git clone https://github.com/oetiker/rrdtool-1.x.git`
Or download the tarball for current master of rrdtool:
https://github.com/oetiker/rrdtool-1.x/archive/master.tar.gz

When using rrdtool from git master, it is recommended to run `./bootstrap` first before `./configure`.
If you want to use rrdtool-1.7.1.tar.gz, you can patch it e.g. using:
https://src.fedoraproject.org/rpms/rrdtool/raw/master/f/rrdtool-1.7.1-compile-fix.patch

**Comment by c72578** [comment] 2019-05-29 04:16
Thanks for your report.
In the meantime, v1.7.2 has been released, where this is fixed.
https://github.com/oetiker/rrdtool-1.x/releases

**Closed by c72578** 2019-05-29 04:16 UTC
