### ISSUE TITLE
Wrong ping values in Cacti graph issue.

### ISSUE THREAD

**Issue by cutehameed** [oetiker/rrdtool-1.x#1183] opened 2022-08-01 04:04 UTC
I am using Cacti as monitoring server and it is working pretty well. But I am facing wrong ping (output) value issue in cacti on only a few graphs. After reading many forums I have come to know this is the appropriate forum to get support. kindly help me in this regards with thanks.

**Comment by c72578** [comment] 2022-08-01 11:41
Duplicate of #1181

**Closed by c72578** 2022-08-01 11:41 UTC
