### ISSUE TITLE
configure script breaks with Python 3.10

### ISSUE THREAD

**Issue by leahneukirchen** [oetiker/rrdtool-1.x#1135] opened 2021-09-27 10:56 UTC
**Describe the bug**

The configure script doesn't detect Python 3.10 properly.

**To Reproduce**
- `install python3.10`
- `./configure --with-python`
```
checking for a Python interpreter with version >= 2.3... python                 
checking for python... /usr/bin/python                                          
checking for python version... 3.1                                              
checking for python platform... linux                                           
checking for python script directory... ${prefix}/lib/python3.10/site-packages  
checking for python extension module directory... ${exec_prefix}/lib/python3.10/
site-packages                                                                   
checking for headers required to compile python extensions... not found         
configure: WARNING: could not find Python headers                               
```

**Expected behavior**

```
checking for python version... 3.10
...
checking for headers required to compile python extensions... found
```                                              

**Desktop (please complete the following information):**
 - OS: Void Linux x86_64/glibc

**Additional context**

The test hardcodes three characters for the python version:
```
  am_cv_python_version=`$PYTHON -c "import sys; sys.stdout.write(sys.version[:3])"`
```

As a workaround, one can pass `am_cv_python_version=3.10` to ./configure, then it works fine.

You should update the `AM_PATH_PYTHON` in `aclocal.m4`.

**Comment by c72578** [comment] 2021-10-01 19:37
@leahneukirchen this does not look like an issue caused by RRDtool.
See a current Fedora build log [1]:
```console
checking for a Python interpreter with version >= 2.3... python3
checking for python3... /usr/bin/python3
checking for python3 version... 3.10
checking for python3 platform... linux
checking for python3 script directory... ${prefix}/lib/python3.10/site-packages
checking for python3 extension module directory... ${exec_prefix}/lib64/python3.10/site-packages
checking for headers required to compile python extensions... found
```

Involved package versions, e.g. automake 1.16.2 [2]

[1] https://kojipkgs.fedoraproject.org//packages/rrdtool/1.7.2/21.fc35/data/logs/x86_64/build.log
[2] https://kojipkgs.fedoraproject.org//packages/rrdtool/1.7.2/21.fc35/data/logs/x86_64/root.log

**Comment by c72578** [comment] 2021-10-01 19:44
This is how it has been fixed in Fedora for automake-1.16.2:
https://src.fedoraproject.org/rpms/automake/c/3327906e94b767330433fda3da2d0997292c55ad?branch=rawhide

**Comment by leahneukirchen** [comment] 2021-10-01 20:08
Yes, reconfiguring with a new automake fixes it.

Still, the configure script in the latest release tarball is broken.

**Comment by c72578** [comment] 2021-10-01 20:38
In order to avoid this, `./bootstrap` should be run first.

**Closed** 2021-10-03 06:31 UTC
