### ISSUE TITLE
I18N Problem - with de_DE.UTF-8 "Week" being printed instead of "Woche"

### ISSUE THREAD

**Issue by devZer0** [oetiker/rrdtool-1.x#436] opened 2014-01-01 20:36 UTC
Hi, 
i`m using rrdtool with LC_ALL=de_DE.UTF-8.

When creating graphs, rrdgraph basically is able to generate the x-axis labelling correctly, i.e. when creating a graph for the last months, it prints "Mo Di Mi Do Fr Sa So", which are the correct german abbreviations for the Days in a week.
When creating a graph for the last year, rrdgraph correctly creates the german abbreviations for the months: Jan, Feb, Mär, Apr, Mai, Jun, Jul, Aug...

This is a nice feature !

BUT - when creating a graph for the last quarter (3 Months), the x-axis shows "Week 49, Week 50, Week 51....".

It seems for the string "Week" there is no I18N being done, as grepping for "Week" inside the source gives :

rrd_graph.c:char week_fmt[128] = "Week %V";

With de_DE.UTF-8,  rrdtool should print "Woche" instead of "Week".

looks like a bug or a missing feature to me.

**Comment by nirgal** [comment] 2015-08-11 20:07
Duplicate of #108 ?

**Comment by oetiker** [comment] 2015-08-13 15:23
in 1.5 graph there is the option week-fmt to specify your week format ... default is "Week %V"

**Closed by oetiker** 2015-08-13 15:23 UTC
