### ISSUE TITLE
RRDTOOL Dump the RRDTOOL RESTORE

### ISSUE THREAD

**Issue by malkahtani** [oetiker/rrdtool-1.x#1127] opened 2021-08-15 05:38 UTC
in this bug https://github.com/oetiker/rrdtool-1.x/issues/1126

I used RRDTOOL to create XML files. However, the files were not written in correct form to be restore. What are the flags that ensure the generation of XML files that can be restored. Flags for validation and correct or replace in case of a missing tag of correct XML format.

**Comment by c72578** [comment] 2021-09-25 04:55
Duplicate of #1126

**Closed by c72578** 2021-09-25 04:55 UTC
