### ISSUE TITLE
<t>timestamp</t> not printed with version 1.5.4 and above

### ISSUE THREAD

**Issue by henkela** [oetiker/rrdtool-1.x#718] opened 2016-07-08 12:00 UTC
Hi, 
we have ganglia 3.7.2 running and use rrd 1.5.4. Wenn I call rrdtool xport I only get the values but if I use an older version like 1.4.x or 1.3.8 also the <t></t> is inside the row. Has something substantially changed with rrdtool xport when moving to 1.5+ or is this a config issue. 
Thanks in advance. 
Best regards, 
Andreas

**Comment by oetiker** [comment] 2016-07-08 12:04
this is a duplicate of #672

**Closed by oetiker** 2016-07-08 12:04 UTC
